version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - nextjs_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev

volumes:
  nextjs_node_modules:
